### ISSUE TITLE
TextView losing selection when Shift+LMB

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#153]
If we press Shift and then quickly click LMB - we will lose text selection.
 
I looked at AppInstance.DispatchEvent() and the only thing that comes to mind - grab 'fresh' _modifiers inside of 'Case SDL_MOUSEBUTTONDOWN'.

**Comment by coconcode** [comment]
Here is my experiment on this problem:
http://monkey2.monkey-x.com/forums/topic/mojox-textview-selecting-with-shift-behaviour/

**Comment by blitz-research** [comment]
Ok, should be fixed now.

This was ultimately due to the fact SDL includes the state of the key modifiers as they were *before* an event along with each event. So for example, if  SDL sent you a 'shift key down' event, the modifiers included with that event WOULD NOT include 'shift'.

Monkey2 doesn't do this, so if you get a 'shift key down' event, the event modifiers DO include 'shift'. As far as I can see, this is not a big deal either way, but it could be changed if necessary.

**Comment by coconcode** [comment]
Strange design decision by the SDL team but anyway... :)
