### ISSUE TITLE
TextView: incorrect numpad behaviour

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#162]
Numpad behaviour has been changed at one time - maybe when you changed event modifiers.

And mojox.TextView works unexpected now:
when we press 2 on numpad we got two events - keydown and keychar.
expect: just insert char '2'
got: move cursor down and insert char '2'.

**Comment by blitz-research** [comment]
This should be fixed now on Windows/Linux in develop branch.

Macos is doing something weird though - gonna leave it alone until I can
get a mac keyboard.

Linux is also doing something weird - numlock light is on when it's off and
vice versa - but it doing it for all apps, not just mx2/sdl apps, so a bit
beyond my scope!

**Comment by retropipes** [comment]
@blitz-research I've noticed unusual behavior with the numeric keypad and macOS myself. It's happening because macOS has no native "Num Lock" concept - the OS treats the keypad as if Num Lock was always on and cannot be disabled. Interestingly, if using a Mac keyboard to run Windows or Linux, Num Lock CAN be engaged/disengaged via the otherwise unused Clear key, which occupies the same position the Num Lock key does on a standard PC keyboard.

**Comment by blitz-research** [comment]
What exactly needs to be done here?
