### ISSUE TITLE
Improve: TextView > TextHighlighter > pass _text into highlighter by pointer

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#171]
String is a struct and copied as value when passed as func param.
TextView's text can be large, a few thousands lines.
And whole this text passed all time into TextHighlighter.
Is it good?
I think, a better way is to pass it as **Ptr** to avoid value-copying.
(and more better would be **const ptr**, be we have nо).

**Comment by blitz-research** [comment]
Strings are actually implemented as reference counted pointers, so copying
a string (passing to function, returning from function, assigning to var
etc) is always 'free' regardless of string length.

This works because strings are immutable, ie: they never change. You can
reassign string variables using '=' or '+=', but you can never modify an
existing string. This mainly works language-wise because I have disallowed
assignment to chars 'in place', eg: 'mystr[i]=65' is not a valid statement.
If it were, strings would no longer be immutable, and I'd have to use COW
or something to deal with fixing reference counts.

I still like to think of strings as value types though, that are
'logically' copied when passed around.

**Comment by engor** [comment]
Nice! :)
And thanks for explanation.
