### ISSUE TITLE
Feature request: eliminate the need to import monkey's modeles by #import

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#179]
I want to use just **Using** directive for importing modules, don't want to know inner modules structure.
I think, translator can do import under the hood.
But leave #Import for including cpp files and so on.

Edited:
Or leave just #Import and make Using optional.

Also: maybe just 'Import' without '#' is simpler to use.

**Comment by blitz-research** [comment]
Nope, modules and namespaces are very different things and I like it that
way. It gives you a huge amount of freedom when it comes to moving stuff
around and deciding where things should go, eg: you can split up a large
module into smaller ones, or combine multiple small modules into a single
large one without have to change any code (except for the #imports).

So a single module can contain multiple namespaces, or symbols in the same
namespace as those declared in an entirely different module. The bottom
line is that module names/paths (and indeed all source file paths) are
completely hidden to the language, which only knows about namespaces and
types etc so modules are effectively completely flexible when it comes to
what you can put in them. It also means one namespace doesn't necessarily
map to one module etc.

One thing I think might be neat is to be able to select the #imported
modules (and indeed all monkey2 source files) in the IDE, and pass them to
mx2cc via command line. This is what c# does and it works well IMO - uses
adds source files (ie: #import "blah") and assemblies (ieL #import
"<blah>") via GUI and these all get passed on the command line.

I would have done something similar with Ted2, but I was wary of adding the
need for a separate 'project' file containing all these 'virtual' #imports.
Another approach would be to 'write' a monkey2 file, say make.monkey2, that
just contains #imports. I sort of do this manually anyway...


On Tue, May 30, 2017 at 8:33 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by retropipes** [comment]
@blitz-research Yes. A "project.monkey2" meta-file, sort of like Python's __init__.py files, used to contain stuff that should be auto-imported when the package is loaded, would be a nice feature! The way this is named is of course up to you to decide, but I think this approach would solve the main problem here.

**Comment by engor** [comment]
> So a single module can contain multiple namespaces, or symbols in the same
> namespace as those declared in an entirely different module.

Hm, and 'using' grab namespaces only from '#imported' modules. Ok. Tx!

What about to use just 'Import' without '#' to be simpler? (like java and others).

**Comment by engor** [comment]
> It also means one namespace doesn't necessarily map to one module etc.

IMO, all namespaces inside of module have to starts with that module's name to avoid import collision.
And then translator can understand exactly what to import accordingly with namespace qualifier.

**Comment by retropipes** [comment]
@engor The issue with dropping the # sign is that Monkey, as far as I know, handles all directives with a pre-processor that only processes lines starting with that character - sort of like how C and C++ implement macros. That change would thus be harder to implement than you'd think.

**Comment by blitz-research** [comment]
> IMO, all namespaces have to starts with module name to avoid import
collision.

This kind of defeats the purpose though, which is basically to make
how/where files are stored completely irrelevant to the language.

IMO, the language shouldn't care how or where source code is stored - it
shouldn't even have to assume that source is stored in files/dirs! It
should only care about logical namespaces/symbols, and provide suitable
mechanisms for resolving collisions. Physical source code could be on the
network somewhere, or in RAM, or in a massive single mega file or
class-per-file for a RAD system or whatever. It doesn't/shouldn't HAVE to
be stored in files in dirs called 'modules'.

Import collisions are avoided by the use of namespaces, and pretty much all
existing modules DO in fact use the name of the module as their 'top level'
namespace. But this is not 'prescribed' by the build system or language, so
module authors have much more flexibility when it comes to deciding where
to put their code. An example of this would be stb-image and stb-vorbis
modules, both of which use 'stb' as the top level namespace. In fact any
mx2 module could very easily be split up into smaller chunks (if we perhaps
decide it's become to heavyweight or something) with very minimal
disruption to #Imports in existing code.

So really, #Import should not IMO be considered part of the language (which
is why I'm reluctant to remove the '#'). It does work subtly differently on
different targets (eg: on macos it has to handle framework imports) and it
is, by necessity, a bit kludgy because it does have to deal with
filesystem/OS issues.

And yes, all this differs massively from Java (and MonkeyX) where
filesystem names effectively *are* namespaces (so filenames must be valid
identifiers and it's not easy to rearrange project structure) but I much
prefer the mx2 way.


On Tue, May 30, 2017 at 9:34 PM, Evgeniy Goroshkin <notifications@github.com
