### ISSUE TITLE
Error : Value 'Self' is not a valid variable reference

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#253]
I wrote
`shape.UserData=Varptr Self`
and got
`Error : Value 'Self' is not a valid variable reference`

Little hack for now is
```
Local me:=Self
shape.UserData=Varptr me
```

**Comment by blitz-research** [comment]
You shouldn't be able to do this, because this effectively allows you to
modify 'Self'.

I may yet make Varptr Object illegal altogether. Note that you can now cast
object's to 'void ptr's (but it's dangerous - be careful!),




On Sat, Oct 28, 2017 at 5:25 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by abakobo** [comment]
Wouldn't it be simpler to receive a warning when trying to varptr an object rather than cast it to void then do it back sometime later..?

@engor : there's a forum topic about chipmunk userData pointers here: http://monkeycoder.co.nz/forums/topic/chipmunk-and-pointers-revisited/

**Comment by engor** [comment]
Solution for me is casting to `void ptr`, thanks!
