### ISSUE TITLE
Version github of monkey2-v1.1.08

### ISSUE THREAD

**Issue by fabiuz** [blitz-research/monkey2#258]
I need compile a source code of version v1.1.08 for linux, but, here in the repository, there is a v1.1.04 version.
There's a v1.1.08 version for windows and mac, but, there is not for linux,

**Comment by fabiuz** [comment]
The tag of repository is indicated the latest version: v1.1.04!!!

**Comment by blitz-research** [comment]
Try the develop branch - I'm planning to update master branch and tag it
this week.

**Comment by arpie42** [comment]
I compiled the develop branch on linux a few days ago and came across one hiccup.  This may now be fixed, but in case it isn't...
The develop branch only has a v1.1.06 binary for linux, which cannot compile version 1.1.08 due to the use of the elvis operator (?) on lines 58 and 69 of file monkey2/src/mx2cc/property.monkey2.  I got round this by manually substituting those two lines with their 1.1.06 equivalents, building the binary once, then switching those lines back to the 1.1.08 versions and recompiling.
I don't think it is possible to get over this issue properly without shipping a 1.1.08 binary.  Perhaps you are planning to do that when you merge into master?  I'm happy to pop my 1.1.08 binary into a pull request if that would be helpful.

**Comment by blitz-research** [comment]
I'm an idiot, thanks for finding this. I do try to avoid using recent lang
features in mx2cc, but obviously missed this one, will 'revert' the mx2cc
source code soon.

I want to avoid updating the binaries as much as possible because it bloats
the repos. I want to make the whole repos 'binary free' eventually, but
that's a big undertaking (for me anyway).

**Comment by blitz-research** [comment]
Changed default github branch to develop.
