### ISSUE TITLE
Issue with List Sort

### ISSUE THREAD

**Issue by nitrologic** [blitz-research/monkey2#26]
The following

```
#import "<std>"
Using std..

Class Cube
    field y:Int
    Global Order:=4 

    Method New(i:Int)
        y=i
    End

    Function CompareCubes:Int(a:Cube,b:Cube)
        Return b.SortDepth(Order)-a.SortDepth(Order)
    End

    Method SortDepth:Int(q:Int)
        Return y
    end
End

Function Main()
    Print "sort test"
    Local list:=New List<Cube>

    list.AddLast(New Cube(0))
    list.AddLast(New Cube(-1))
    list.AddLast(New Cube(1))

    list.Sort(Cube.CompareCubes)
    For Local cube:=Eachin list
        Print cube.y
    next    
end
```

outputs the following

```
0
-1
1
```

**Comment by nitrologic** [comment]
works with struct so maybe an error saying my class is missing some other operator?

**Comment by blitz-research** [comment]
For some reason, it's not actually calling the correct version of Sort() -
it's calling the bool overload instead of the function one.

I suspect it may actually be a c++ issue - bbFunction has a bbBool
conversion operator and c++ might be using that. Will investigate.

Weirdly, it works with lambas though so you can work around it for now by
wrapping the compare call in a lambda.

**Comment by nitrologic** [comment]
Cool, using lambdas now and working fine. Thanks!

**Comment by blitz-research** [comment]
Found the problem (c++ implitctly casting function pointer to bool) - but
it could take a while to fix.

A workaround for now is to change the ascending param of the first
List.Sort (and Stack.Sort) from bool to int.

**Comment by XANOZOID** [comment]
@blitz-research This has been fixed and can be closed :) just tested and results are:
![image](https://user-images.githubusercontent.com/29788070/34325373-cef0a6a8-e84c-11e7-98be-1f6845618628.png)
