### ISSUE TITLE
Font.Load : data.Discart() is missed?

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#276]
https://github.com/blitz-research/monkey2/blob/4399d4be80fd8354460197026869a7a0393bf4e0/modules/mojo/graphics/freetypefont.monkey2#L44

Don't know is it important here, but you try to use databuffer.Discard in all places.

**Comment by blitz-research** [comment]
I think it's correct as is.

FreeTypeFont generates char 'pages' on the fly instead of all at once (as there could theoretically be thousands), so it leaves the freetype font data 'open' for when it needs it - note that 'New FreeTypeFont' passes 'data' to the ctor for later use.

The FreeTypeFont.Discard method is where the data actually gets discarded. although this is strictly no longer needed as resources now use a simple 'finalizer' system to release memory, files, and other OS resources when they become unreachable.

But I do try to be tidy with OS level stuff as finalizers can take a while to run so if I've really missed something here (or anywhere else ) please let me know!
