### ISSUE TITLE
Hardcoded cyrillic strings became abrakabadra, but loaded from file are OK

### ISSUE THREAD

**Issue by engor** [blitz-research/monkey2#277]
Look at attached example.
Hardcoded strings:
![abra-case1](https://user-images.githubusercontent.com/5233803/33193587-57134ef4-d0fc-11e7-93a5-a5e4a5e9e479.png)

The same but loaded from file strings:
![abra-case2](https://user-images.githubusercontent.com/5233803/33193592-66f88d66-d0fc-11e7-80a0-30da7721d642.png)

[abrakadabra.zip](https://github.com/blitz-research/monkey2/files/1500506/abrakadabra.zip)

**Comment by blitz-research** [comment]
Nice one, took me an hour to find but turned out to be stupidly simple -
msvc can't handle utf-8 source files unless they have a BOM marker at the
start! Mingw always assumes source file are utf-8 so this issue doesn't
even occur. But mingw doesn't like BOMs apparently (either do I).

Fortunately, the fix is easy. Just  add the '-utf-8' option to the end
of MX2_CC_OPTS_MSVC and MX2_CPP_OPTS_MSVC in env_windows.txt. This will be
added to next release of course...

I'm actually surprised that SDL can handle the unicode windows title,
according to my calculations it probably shouldn't!

I will take a good look at windows encoding issues very soon, probably just
starting with libc and std.filesystem.





On Fri, Nov 24, 2017 at 3:48 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by blitz-research** [comment]
Fixed.
