### ISSUE TITLE
Dots in filenames?

### ISSUE THREAD

**Issue by blitz-research** [blitz-research/monkey2#307]
http://monkeycoder.co.nz/forums/topic/compiling-problem-report/

**Comment by XANOZOID** [comment]
I can describe the problem a little bit more clearly here as from what I've found:

File names are taken as literals and DOTS in filenames are not filtered/replaced out when that is what seems to be causing the problem.

### The C++ output has the following problems:

- File guards generated by [`TranslateFile`](https://github.com/blitz-research/monkey2/blob/4cb6c8ed22d090f8d400f242b8bdbd9a02a6fa84/src/mx2cc/translator_cpp.monkey2#L165) seem to have dots in their names which causes compile errors.
- Some function names also have the same problem. **_NOTE_** This only applies for functions generated by MX2CC like outputs as `void mx2_<FILE WITH DOT>_std_collections_2container_init_f();mx2_<FILE WITH DOT>_std_collections_2container_init_f();`

### A Solution? 
I think wherever the entry point is, builder(?), should replace dots with something like _DOT_ or an underscore. But I said _DOT_ first because of the off chance some one has a file.name and a file_name. Probably an ignorable case. 
The other thing that might cause problems is the #import statements themselves... Those may need to be filtered appropriately before processing as well... 


I would go ahead and implement it, but I haven't gotten far enough into Monkey2 as to start building the project myself nor have I dug very well into the transpile/building/compiling part of M2...

**Comment by engor** [comment]
Possibly duplicated: https://github.com/blitz-research/monkey2/issues/213

**Comment by blitz-research** [comment]
Fixed in develop.
