### ISSUE TITLE
[Suggestion] Entity.PointAt should operate in world space

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#324]
I made this for myself, but it seems to work much better than the regular PointAt, which fails very easily when dealing with entities in hierarchies. Maybe it should use world space by default?

```
Class Entity Extension
	
	Method WorldPointAt( target:Vec3f,up:Vec3f=New Vec3f( 0,1,0 ) )
		Local k:=(target-Position).Normalize()
		Local i:=up.Cross( k ).Normalize()
		Local j:=k.Cross( i )
		Basis=New Mat3f( i,j,k )
	End

End
```

**Comment by DruggedBunny** [comment]
I've just spent about 30 mins trying to resolve this, until accidentally remembering seeing this post in my emails!

I had a camera hanging from a parent pivot:Model... I moved the pivot and used camera.PointAt, and ended up with nothing in sight!

This code resolved it instantly (well, other than needing the Vec3f instead of an entity!).

EDIT: Also neatly demonstrates how cool Extension is!

**Comment by blitz-research** [comment]
Sorry folks, have a push coming soon that will fix these -  but no doubt
introduce new 'uns!

**Comment by blitz-research** [comment]
Fixed in develop.
