### ISSUE TITLE
Models with alpha sort their own meshes backwards

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#467]
Hi,

While sorting between different models seems to work fine, if a single model has multiple separate pieces they're sorting backwards, like this (A should be in front of B, B in front of C, etc.):
<img width="752" alt="screen shot 2019-01-29 at 12 35 27 pm" src="https://user-images.githubusercontent.com/6250116/51938808-dffc6b00-23c2-11e9-973b-fc7beeb25da3.png">

Here's the example file, with assets.
[AlphaTest.zip](https://github.com/blitz-research/monkey2/files/2809583/AlphaTest.zip)

There's also a tree model, you can see how the leaf cards are rendered behind the leaf "bag" that should be the innermost mesh. Walk around with WASD keys and Mouse look.

(By the way, the only way I know to enable alpha textures without making a whole object transparent is by making its alpha 0.999... not sure there's a better way).

**Comment by nitrologic** [comment]
didn't you fix this in toy plane demo?

"name": "Canopi",
"emissiveFactor": [
0,
0,
0
],
"pbrMetallicRoughness": {
"baseColorFactor": [
0.15294117647058825,
0.27058823529411763,
0.21568627450980393,
0.43
],
"metallicFactor": 0.23,
"roughnessFactor": 0
},
"alphaMode":"BLEND"
}

**Comment by nitrologic** [comment]
Microsoft 3D viewer also has issues with tree.gltf but renders slices.gltf in correct order. Playing with alphaMode did not seem to help when testing.

**Comment by DoctorWhoof** [comment]
None of those files have the correct blend mode because Houdini's GLTF implementation is still basic (no transparency, no animation, etc.). But even if the GLTF file has the correct blend mode (or if you override it by code, like I'm doing), the sorting is still wrong in the mojo3d side if the mesh contains more than one piece.

Thanks!

**Comment by blitz-research** [comment]
The slices model cannot be sorted properly because it's just a single
'polygon soup' mesh, and mojo3d can't/wont sort individual polygons, it can
only sort 'surfaces', ie: a mesh+material batched render op. You must have
used vertex coloring to get individual slice colors?

Mojo3d currently sorts transparent surfaces within models 'by entity
origin' which means that one way to fix this would be to change the model
so each slice is a distinct child entity with a non-zero local origin. This
also means you can't currently add a bunch of transparent surfaces to a
model and expect them to sort  properly, becuase they'll all be sorted by
the same position, ie: the entity's origin.

But  I have also just experimented with tweaking the engine so that it
sorts transparent surfaces 'by surface bounds center' which would fix this,
but it'd only be as good as transparent sorting routines can be (which
cannot be 100% reliable - which of these should be drawn first?
https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Painters_problem.svg/1024px-Painters_problem.svg.png
).

But this would at least be enough to allow you to add windows to building
etc, and would fix your slices problem - the only problem is I don't have a
model to test with! Would you be able to update the slices model so it
contains 4 distinct meshes, one for each slice, instead of a single blob
mesh?

Also, instead of `Slices.Alpha=0.999` you can use
`slices.Materials[0].BlendMode = BlendMode.Alpha`

**Comment by DoctorWhoof** [comment]
Thanks Mark! The individual slices use offset texture coordinates, and a single texture containing 4 tiles.

I understand the problem, and seems like sorting by surface bounds center would be good enough!

I can also switch to generating individual slices, the problem in that case is not with Mojo3D but with Houdini, whose GLTF exporter doesn't do a good job with instances yet (everything is exported as unique objects, and that kills my frame rate when I have a lot of instances). It's an early exporter version, so I expect it to improve soon.

I will try to export to uniquely named pivots instead, and replace them at runtime with properly cloned meshes on the Mojo3D side.

Here's a zip containing two gltf files, ones where the slices are combined, and one where they are separated.

[slices.zip](https://github.com/blitz-research/monkey2/files/2825128/slices.zip)

Thanks!

**Comment by blitz-research** [comment]
Hmm, I can no longer run FPTtest with slices_separate.gltf due to child
naming issues, but the new model isn't quite what I was after anyway.

Instead of a creating a new child node for each 'slice', I was hoping there
would still only be one node, but with 4 'surfaces' (or primitives as
they're called in gltf). Is this doable or is it a problem with Houdini?

A separate entity per transparent surface should indeed work, ala the
'alphacubes' test, but as you say it'll hurt performance.

[edit]
I have successfully hacked the gltf file you sent in a text editor to get
the desired result in FPSTest and it seems to work!

Note: since there are multiple surfaces in the model, you need to do
something like this to make all surfaces transparent:

For Local i:=0 Until slices.Materials.Length
slices.Materials[i].CullMode = CullMode.None
slices.Materials[i].BlendMode = BlendMode.Alpha
Next

I've attached the new gltf file, but you'll also need to pull develop
branch to get more precise surface sorting. Notice that the new gltf only
has 2 nodes, but the mesh node now contains 4 'primitives'.

I've also noticed that 'double sided' lighting doesn't work quite right,
the surface normal should really be negated if the surface is backfacing,
will look into how to do this, I seem to remember something like
gl_FrontFacing...
[/edit]

**Comment by DoctorWhoof** [comment]
I don't see any change in the dev branch, did you push it?

Anyway, I tried an option called "packed copies" in Houdini, its equivalent of instances.
It seems to load as a single model in mojo3d, but I can't tell for sure if each instance is indeed a gltf surface, instead of part of a polygon soup. 

[packed_copies.zip](https://github.com/blitz-research/monkey2/files/2825976/packed_copies.zip)

Here's how it looks in Ted2Go, currently. The same sorting issue, but in a different order than before:
<img width="432" alt="screen shot 2019-02-03 at 12 46 25 pm" src="https://user-images.githubusercontent.com/6250116/52182408-c3d93f00-27b1-11e9-874d-51d0e984feff.png">

Maybe this is what you're looking for? My only other options are one entity per mesh, or all meshes combined into a single one (Polygon soup).

**Comment by blitz-research** [comment]
> did you push it?

Thought I had but I guess not!

At work right now but I'll fix when I get home...

**Comment by blitz-research** [comment]
Ok, pushed now. Houdini sounds a bit limited here, can you really not have
a single node that contains multiple materials? This is the only thing
really needed for this to work, ie: each transparent 'submesh' needs it's
own material.

But slices_separate.gltf can be made to work with normal mojo3d, you just
need to be a bit careful finding all the child models as mojo3d inserts an
extra node at the root (sometimes)? Something like EnumChildEntities<T>
might be useful here....

And it turns out you can use the new sorting method too by using Model.Load
instead of Model.LoadBoned, which will collapse the hierarchy into a single
model with multiple surfaces, eg:

```
Local slicesModel := Model.Load( "asset::slices_separate.gltf")  'NOT
LoadBoned!

slicesModel.Alpha=.7   'just for testing...

For Local material:=Eachin slicesModel.Materials
material.CullMode=CullMode.None
material.BlendMode=BlendMode.Alpha    'only really needed if you're not
setting entity Alpha.
Next
```

This appears to work fine and should be faster than the LoadBoned version,
but it'd be better if you can convince Houdini to do this for you of
course...

**Comment by DoctorWhoof** [comment]
Houdini can definitely do multiple materials per mesh, but I was avoiding that since the goal was to render a large number of instanced meshes as fast as possible, so I was trying to use the same exact material on each one (i.e. the branches on a tree, then the tree model itself is copied hundreds of times).

Got the latest dev branch, will test it tomorrow.
Thanks!

**Comment by blitz-research** [comment]
> the goal was to render a large number of instanced meshes as fast as
possible .

This is hard, especially with transparency. Mojo3d will already 'resuse'
the same mesh/vbuffers/ibuffers if you copy a model, but there will still
be considerable 'per-entity' and 'per-material' overhead, and this is the
real killer.

The fastest way to go for opaque surfaces in most cases is probably to just
draw a single 'mega mesh' that uses a single material. Even if it may take
up more memory on the GPU than using many instances of the same mesh, it's
still likely to be faster than drawing N instances of something. But of
course this is useless for transparency, since surfaces must still be
sorted so the mesh would have to be recreated every frame.

OpenGLES3 does allow you to 'instance' meshes which allows you to use the
same mesh over and over by giving you access to an 'instanceId' value in
the vertex shader, but mojo3d wont be going there yet, and it still doesn't
solve the need to sort transparent surfaces.

The ultimate solution to alpha issues would be some kind of 'order
independent transparency' system, where it doesn't matter what order you
draw transparent stuff:

http://casual-effects.blogspot.com/2015/03/implemented-weighted-blended-order.html

But I haven't really looked into that very much.

**Comment by DoctorWhoof** [comment]
Thanks Mark, I think I have enough information to now to work around the issue on the asset creation side. I'll close it, but feel free to reopen the issue in case you want to keep track of it.

Cheers!
